package nginx

import (
	"context"
	"testing"

	"github.com/crenelhq/crenel/internal/model"
)

// TestNormalize_DetectsNPMForeign proves P2 generator detection: an Nginx Proxy
// Manager-generated config is recognized read-only and marked FOREIGN-managed
// (edge-wide + per-route), so the refuse-to-manage gate will block any mutation —
// NPM regenerates these files from its DB, so a crenel edit would be reverted.
func TestNormalize_DetectsNPMForeign(t *testing.T) {
	cfg := `# ------------------------------------------------------------
# grafana.example.com
# ------------------------------------------------------------
# this configuration file is generated by Nginx Proxy Manager
server {
    listen 443 ssl;
    server_name grafana.example.com;
    location / {
        proxy_pass http://10.0.0.5:3000;
    }
}
`
	d := New(tempConfig(t, cfg), resolver())
	live, err := d.ReadLiveState(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if live.Generator != "nginx-proxy-manager" {
		t.Fatalf("expected NPM generator detection, got %q", live.Generator)
	}
	if !live.HasHost("grafana.example.com") {
		t.Fatalf("the route should still be READ (understanding != ownership), got %v", live.Hosts())
	}
	for _, r := range live.Routes {
		if r.Ownership != model.OwnForeign || r.Managed {
			t.Errorf("a generator-owned route must be foreign + unmanaged, got %+v", r)
		}
	}
}

// TestNormalize_NoGeneratorForPlainConfig guards against false positives: an
// ordinary operator-written config is NOT flagged as generator-owned.
func TestNormalize_NoGeneratorForPlainConfig(t *testing.T) {
	d := New(tempConfig(t, richFixture), resolver())
	live, err := d.ReadLiveState(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if live.Generator != "" {
		t.Errorf("a hand-written config must NOT be flagged generator-owned, got %q", live.Generator)
	}
}
