package core_test

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/crenelhq/crenel/internal/core"
	"github.com/crenelhq/crenel/internal/drivers/edge/caddy"
	"github.com/crenelhq/crenel/internal/drivers/edge/caddy/caddyfake"
	"github.com/crenelhq/crenel/internal/drivers/edge/nginx"
	"github.com/crenelhq/crenel/internal/drivers/origin/static"
	"github.com/crenelhq/crenel/internal/model"
)

// TestGenerator_EndToEndRefusesNPMEdge proves the P2 detection → P0 gate pipeline on
// a REAL driver: core drives an nginx edge whose config is generated by Nginx Proxy
// Manager; status reports it FOREIGN-MANAGED, audit warns ownership_unconfirmed, and
// any mutation (even an additive expose) is refused by the gate — never edited and
// silently reverted.
func TestGenerator_EndToEndRefusesNPMEdge(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "edge.conf")
	npm := `# this configuration file is generated by Nginx Proxy Manager
server {
    listen 443 ssl;
    server_name grafana.example.com;
    location / {
        proxy_pass http://10.0.0.5:3000;
    }
}
`
	if err := os.WriteFile(path, []byte(npm), 0o644); err != nil {
		t.Fatal(err)
	}
	res := static.New(map[string]string{"grafana": "10.0.0.5:3000", "photos": "10.0.0.6:2342"})
	e := core.New(nginx.New(path, res), "example.com")
	ctx := context.Background()

	// status: FOREIGN-MANAGED, route read but foreign-owned.
	st, err := e.Status(ctx)
	if err != nil {
		t.Fatal(err)
	}
	es := st.Edges[0]
	if es.Generator != "nginx-proxy-manager" {
		t.Fatalf("status should report the NPM generator, got %q", es.Generator)
	}

	// audit: ownership_unconfirmed naming the generator.
	rep, err := e.Audit(ctx)
	if err != nil {
		t.Fatal(err)
	}
	f, ok := findCode(rep, "ownership_unconfirmed")
	if !ok || !strings.Contains(f.Message, "nginx-proxy-manager") {
		t.Errorf("audit should flag ownership_unconfirmed naming the generator, got %+v", rep.Findings)
	}

	// gate: an additive expose onto the generator-owned edge is refused (even --yes).
	_, err = e.Apply(ctx, e.BuildOp(model.Expose, "photos"), core.AlwaysYes)
	if err == nil || !errors.Is(err, core.ErrRefuseToManage) {
		t.Fatalf("expose onto a generator-owned edge must refuse, got %v", err)
	}
	// And so is an unexpose of the foreign route.
	_, err = e.Apply(ctx, e.BuildOp(model.Unexpose, "grafana"), core.AlwaysYes)
	if err == nil || !errors.Is(err, core.ErrRefuseToManage) {
		t.Fatalf("unexpose of a generator-owned route must refuse, got %v", err)
	}

	// The config file is byte-for-byte untouched (read-only-safe by construction).
	after, _ := os.ReadFile(path)
	if string(after) != npm {
		t.Errorf("a refused mutation must not have written the file")
	}
}

// TestGenerator_EndToEndRefusesCaddyDockerProxyEdge proves the P2 detection → P0 gate
// pipeline for caddy-docker-proxy: pointed at CDP's on-disk `Caddyfile.autosave`, core
// reports the Caddy edge FOREIGN-MANAGED, audit warns ownership_unconfirmed, and any
// mutation (even an additive expose) is refused — and the live admin config is left
// untouched (read-only-safe).
func TestGenerator_EndToEndRefusesCaddyDockerProxyEdge(t *testing.T) {
	fake := caddyfake.New()
	defer fake.Close()
	cdp := `{"apps":{"http":{"servers":{"srv0":{"listen":[":443"],"routes":[
		{"match":[{"host":["whoami.example.com"]}],"handle":[{"handler":"reverse_proxy","upstreams":[{"dial":"whoami:80"}]}]}
	]}}}}}`
	if err := fake.SeedJSON(cdp); err != nil {
		t.Fatal(err)
	}
	autosave := filepath.Join(t.TempDir(), "Caddyfile.autosave")
	if err := os.WriteFile(autosave, []byte("whoami.example.com {\n\treverse_proxy whoami:80\n}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	res := static.New(map[string]string{"grafana": "10.0.0.5:3000", "photos": "10.0.0.6:2342"})
	prov := caddy.New(fake.URL(), res, caddy.WithGeneratorConfigPath(autosave))
	e := core.New(prov, "example.com")
	ctx := context.Background()

	st, err := e.Status(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if st.Edges[0].Generator != "caddy-docker-proxy" {
		t.Fatalf("status should report the CDP generator, got %q", st.Edges[0].Generator)
	}

	rep, err := e.Audit(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if f, ok := findCode(rep, "ownership_unconfirmed"); !ok || !strings.Contains(f.Message, "caddy-docker-proxy") {
		t.Errorf("audit should flag ownership_unconfirmed naming CDP, got %+v", rep.Findings)
	}

	before := fake.CurrentJSON()
	// An additive expose onto the generator-owned edge is refused (even --yes).
	if _, err := e.Apply(ctx, e.BuildOp(model.Expose, "photos"), core.AlwaysYes); err == nil || !errors.Is(err, core.ErrRefuseToManage) {
		t.Fatalf("expose onto a CDP-owned edge must refuse, got %v", err)
	}
	if after := fake.CurrentJSON(); after != before {
		t.Errorf("a refused mutation must not have changed the live config")
	}
}
